### ISSUE TITLE
QA: Edge 15 and IE 11: E-Commerce Opportunities Bar is not Sticky on Edge

### ISSUE THREAD

**Issue by pascale-georges** [vigetlabs/pointed-ecommerce#18]
URL: [Explorations: Improving the Way We Shop Online](http://code.viget.com/pointed-ecommerce/)

The e-commerce opportunities bar isn't sticking to the top of the page as you scroll on Edge and IE 11. Screenshot of the bar below for reference:

![screen shot 2017-08-09 at 5 22 22 pm](https://user-images.githubusercontent.com/25062777/29144541-552463cc-7d27-11e7-971a-583a1fbb4512.png)

**Comment by chloehwang** [comment]
@ten1seven and I were thinking that since this is an internal project, we can let it gracefully degrade on IE/Edge and not add a polyfill to make it work. how does that sound?

**Comment by pascale-georges** [comment]
That works for me. Thanks @chloehwang. Closing this one.
