### ISSUE TITLE
QA: Mobile: E-Commerce Opportunities Menu Item 

### ISSUE THREAD

**Issue by pascale-georges** [vigetlabs/pointed-ecommerce#20]
If I click an e-commerce opportunity item (Social Validation, for example), I'm led down to the appropriate section of the page. This behavior is expected. 

When I scroll back up to view the e-commerce opportunity menu, Social Validation is still highlighted in the menu. When you users scroll back up to the menu, would it be possible to display the e-commerce opportunity links in their default state (all white links)? 

![screen shot 2017-08-10 at 1 05 01 pm](https://user-images.githubusercontent.com/25062777/29182760-106a3fa2-7dce-11e7-9f31-3c4ef9a9b131.png)

**Comment by pascale-georges** [comment]
@chloehwang the e-commerce opportunities links still behave the same way. Let me know if there's a way to adjust the links. If not, I don't think ti's a deal breaker.

**Comment by chloehwang** [comment]
@pascale-georges hmmmm strange, it is working for me. Can you try doing a hard refresh? Maybe the stylesheet got cached.

**Comment by pascale-georges** [comment]
Thanks for fixing it. It looks good on my phone.
