### ISSUE TITLE
Add FB and Twitter Share Images 

### ISSUE THREAD

**Issue by beneckerson** [vigetlabs/pointed-ecommerce#23]
OG / Social Sharing images to add @chloehwang (it's not letting me assign you to the issue)

Facebook:

![explorations-ecomm-fb](https://user-images.githubusercontent.com/926855/29478795-cced1ebe-843c-11e7-9cfc-4ca22863cb2a.jpg)

Twitter:

![explorations-ecomm-twitter](https://user-images.githubusercontent.com/926855/29478802-d743f7b6-843c-11e7-8ce8-b374702549c1.jpg)

**Comment by btrav** [comment]
Note that we also need a description @beneckerson

**Comment by beneckerson** [comment]
Yep - provided those to @chloehwang 

Title
Improving the Way We Shop Online: A Viget Exploration

One-Line Description
E-commerce is still focused on buying rather than shopping. This exploration attempts to bridge the gap between physical and digital.

One-Paragraph Description
What’s missing from the online shopping experience? Most of the experience itself, it turns out. E-commerce is still focused on buying rather than shopping. Digital agency Viget explores ways to bridge the gap between physical and digital.

**Comment by chloehwang** [comment]
@beneckerson done and on staging
