### ISSUE TITLE
Panel for Explorations.Viget.com

### ISSUE THREAD

**Issue by beneckerson** [vigetlabs/pointed-ecommerce#24]
Need to design a Panel for the list on explorations.viget.com.

Need to assign this to Mihn somehow...

**Comment by beneckerson** [comment]
We need a panel like this:

 
![screen shot 2017-08-22 at 10 20 42 am](https://user-images.githubusercontent.com/926855/29570154-9a903476-8723-11e7-94f4-5ec48caf7262.png)

**Comment by beneckerson** [comment]
![fg-ecomm](https://user-images.githubusercontent.com/926855/29573183-59a178a4-872c-11e7-9772-6ff56fea4716.png)
![bg-ecomm](https://user-images.githubusercontent.com/926855/29573184-59a2074c-872c-11e7-8bf5-8fb2b1efff5c.jpg)
![explorations-ecomm-panel](https://user-images.githubusercontent.com/926855/29573185-59c2a024-872c-11e7-8c86-a65fdbdfe3ff.jpg)

**Comment by chloehwang** [comment]
@beneckerson The panel looks like this right now, is this what we want? It's a bit taller than the other panels in order to fit the shoes.

![screen shot 2017-08-24 at 4 30 01 pm](https://user-images.githubusercontent.com/22921416/29687215-8deb1872-88e9-11e7-9238-21b7b3420c1e.png)

**Comment by beneckerson** [comment]
I think it's okay - could we clip the shoes a hair more or scale them down a smidge to try and bring it even?

**Comment by chloehwang** [comment]
@beneckerson yes no problem, but what do you mean by "bring it even"?

**Comment by beneckerson** [comment]
Sorry - "even height"
