### ISSUE TITLE
Add Share buttons

### ISSUE THREAD

**Issue by beneckerson** [vigetlabs/pointed-ecommerce#25]
Like all the other sites, we need to add the Facebook Like button and Tweet button. 

Looking for direction from Minh (on where) then @chloehwang can drop in.

**Comment by chloehwang** [comment]
@beneckerson How do I go about registering a new app for FB? Should I create one on my personal account?

**Comment by beneckerson** [comment]
No I think you can use the Viget account - perhaps @cwmanning can help?

**Comment by cwmanning** [comment]
@chloehwang I haven't added a like button in a while, but here's an example of the last time I did it, with an app ID that should work for this project: https://github.com/vigetlabs/fantasyfootball/blob/c6b5d1d9507d6eb8953cd965fe890eb855517b9e/src/html/index.html#L14. Available if you have any questions!

**Comment by beneckerson** [comment]
This looks done @chloehwang - no?

**Comment by chloehwang** [comment]
@beneckerson done and on staging
