### ISSUE TITLE
Move Site from code.viget to explorations.viget (proper URL)

### ISSUE THREAD

**Issue by beneckerson** [vigetlabs/pointed-ecommerce#28]
Please move the site to explorations.viget.com/onlineshopping

**Comment by beneckerson** [comment]
@chloehwang once we close up the other issues, I can get a dev to help us with this step...

**Comment by solomonhawk** [comment]
@chloehwang Any follow-ups here? Are we good to go?

**Comment by chloehwang** [comment]
@solomonhawk nothing left, it's good to go!
